apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  DB_HOST: "postgres-service.devops.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "devopsdb"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: devops
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQxMjM=
  SECRET_KEY: c2VjcmV0a2V5MTIz